import { StyleSheet } from "react-native";
import {
  dark,
  main,
  light,
  disabled,
  secondary,
  mainLighter,
  mainLight,
} from "../ColorPallete";

export const GeneralComponentsStylesheet = StyleSheet.create({
  buttonContainer: {
    backgroundColor: light,
    display: "flex",
    flex: 1,
  },
  buttonTitleStyle: {
    fontSize: 20,
  },
  buttonMain: {
    backgroundColor: main,
    justifyContent: "center",
    alignSelf: "center",
    color: light,
    width: "90%",
    padding: 10,
    height: 70,
    borderRadius: 20,
  },
  darkTheme: {
    backgroundColor: dark,
    flex: 1,
    justifyContent: "center",
  },
  lightTheme: {
    backgroundColor: light,
    flex: 1,
    justifyContent: "center",
  },
  typographyNormal: {
    textAlign: "center",
    fontFamily: "System",
    color: main,
    fontSize: 18,
  },
  typographyBold: {
    textAlign: "center",
    fontFamily: "System",
    fontWeight: "bold",
    color: main,
    fontSize: 18,
  },
  typographyNormalWhite: {
    textAlign: "center",
    fontFamily: "System",
    color: light,
    fontSize: 30,
  },
  typographyCaptionWhite: {
    textAlign: "center",
    fontFamily: "System",
    color: light,
    opacity: 0.7,
    fontSize: 20,
  },
  typographyBoldWhite: {
    textAlign: "center",
    fontFamily: "System",
    fontWeight: "bold",
    color: light,
    fontSize: 50,
  },
  formContainer: {
    backgroundColor: light,
    display: "flex",
    flex: 2,
    paddingTop: 50,
    paddingBottom: 20,
    flexDirection: "column",
    justifyContent: "center",
  },
  inputStyle: {
    color: main,
    borderRadius: 20,
    height: 70,
    borderColor: "transparent",
    backgroundColor: disabled,
  },
  tabButtonRight: {
    backgroundColor: light,
    color: main,
    display: "flex",
    justifyContent: "center",
    borderTopRightRadius: 20,
  },
  tabButtonLeft: {
    backgroundColor: light,
    color: main,
    display: "flex",
    justifyContent: "center",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  inactiveTabButtonRight: {
    borderBottomLeftRadius: 20,
    backgroundColor: main,
    color: light,
  },
  inactiveTabButtonLeft: {
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: main,
    color: light,
  },
  homeHeader: {
    display: "flex",
    flex: 1,
    backgroundColor: main,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 20,
    paddingTop: 20,
  },
  homeTabContainer: {
    display: "flex",
    flex: 2,
  },
  shortcutTabContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 20,
  },
  shortcutTabIconWrapper: {
    display: "flex",
    height: 70,
    width: 70,
    backgroundColor: mainLighter,
    opacity: 0.7,
    borderRadius: 20,
    justifyContent: "center",
  },
});
